services:
  backend:
    image: "backend"
    build: ./backend
    container_name: backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./env/backend.env
      - ./env/config.env
    logging:
      driver: "json-file"
      options:
        max-file: "3" # number of files or file count
        max-size: "5m" # file size

  frontend:
    image: "react-vite-ts:v1.0.1"
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    env_file:
      - ./env/frontend.env
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-file: "3" # number of files or file count
        max-size: "5m" # file size

